[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rwa_solana = "3PJVuFionEzADePhZJ5u3h81q5d6EmQ8JiM2cqCp7zPA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
